#!/usr/bin/env python3
"""
Export Caption-Voiceover-Writer captions to a formatted .docx file.

This script is bundled with the caption-voiceover-writer skill and can be called
to generate polished .docx files from caption data.

Usage:
    python export_captions_to_docx.py --brand "OutAtlas" --output "OutAtlas_Captions_03282026.docx" --captions captions_data.json

The script expects captions_data.json in the following format:
{
  "brand": "OutAtlas",
  "date_range": "Mar 28 - Apr 3, 2026",
  "posts": [
    {
      "number": 1,
      "title": "Post Title",
      "date": "2026-03-28",
      "asset_type": "Photo",
      "platforms": {
        "TikTok": {
          "caption": "...",
          "hashtags": "...",
          "cta": "..."
        },
        "Instagram Reels": { ... }
      },
      "voiceover": {
        "tone": "Friendly & warm",
        "duration_sec": 30,
        "script": "...",
        "delivery_notes": "...",
        "ai_option": { ... }
      }
    }
  ]
}
"""

import json
import argparse
from datetime import datetime
from pathlib import Path
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

# Brand color mappings
BRAND_COLORS = {
    "OutAtlas": RGBColor(56, 189, 153),  # teal #38bd99
    "Travel in Pride": RGBColor(245, 192, 110),  # gold #f5c06e
}

def create_docx_from_captions(brand, date_range, posts, output_path):
    """Create a formatted .docx file from caption data."""

    doc = Document()

    # Set default font
    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # Title section
    title = doc.add_paragraph()
    title.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    title_run = title.add_run(f"{brand.upper()}")
    title_run.font.size = Pt(24)
    title_run.font.bold = True
    title_run.font.color.rgb = BRAND_COLORS.get(brand, RGBColor(0, 0, 0))

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    subtitle_run = subtitle.add_run("Caption & Voiceover Script Collection")
    subtitle_run.font.size = Pt(14)
    subtitle_run.font.italic = True

    # Date range
    date_para = doc.add_paragraph()
    date_para.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    date_run = date_para.add_run(date_range)
    date_run.font.size = Pt(11)

    # Generated by
    gen_para = doc.add_paragraph()
    gen_para.paragraph_format.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    gen_run = gen_para.add_run("Generated by: Caption-Voiceover-Writer Skill")
    gen_run.font.size = Pt(10)
    gen_run.font.italic = True
    gen_run.font.color.rgb = RGBColor(128, 128, 128)

    # Add divider
    doc.add_paragraph("━" * 80)

    # Table of contents
    toc_heading = doc.add_heading('TABLE OF CONTENTS', level=2)
    toc_heading.style.font.color.rgb = BRAND_COLORS.get(brand, RGBColor(0, 0, 0))

    for post in posts:
        toc_entry = doc.add_paragraph(f"POST {post.get('number', '?')}: {post.get('title', 'Untitled')}", style='List Bullet')
        toc_entry.paragraph_format.left_indent = Inches(0.25)

    doc.add_paragraph("━" * 80)
    doc.add_paragraph()

    # Process each post
    for post in posts:
        post_heading = doc.add_heading(
            f"POST {post.get('number', '?')} — {post.get('title', 'Untitled')}",
            level=1
        )
        post_heading.style.font.color.rgb = BRAND_COLORS.get(brand, RGBColor(0, 0, 0))

        # Post metadata
        meta_table = doc.add_table(rows=1, cols=3)
        meta_table.style = 'Light Grid Accent 1'

        meta_cells = meta_table.rows[0].cells
        meta_cells[0].text = f"Date: {post.get('date', 'TBD')}"
        meta_cells[1].text = f"Brand: {brand}"
        meta_cells[2].text = f"Asset: {post.get('asset_type', 'Unknown')}"

        doc.add_paragraph()

        # Platform captions
        platforms = post.get('platforms', {})
        for platform, caption_data in platforms.items():
            platform_heading = doc.add_heading(platform, level=3)

            # Caption text
            caption_para = doc.add_paragraph(caption_data.get('caption', ''), style='List Paragraph')
            caption_para.paragraph_format.left_indent = Inches(0.25)

            # Hashtags
            hashtags_para = doc.add_paragraph()
            hashtags_label = hashtags_para.add_run("Hashtags: ")
            hashtags_label.italic = True
            hashtags_run = hashtags_para.add_run(caption_data.get('hashtags', ''))
            hashtags_run.font.color.rgb = RGBColor(128, 128, 128)

            # CTA
            cta_para = doc.add_paragraph()
            cta_label = cta_para.add_run("CTA: ")
            cta_label.italic = True
            cta_run = cta_para.add_run(caption_data.get('cta', ''))

            doc.add_paragraph("─" * 40)
            doc.add_paragraph()

        # Voiceover script (if present)
        voiceover = post.get('voiceover', {})
        if voiceover and voiceover.get('script'):
            vo_heading = doc.add_heading('VOICEOVER SCRIPT', level=3)

            # Tone and duration
            tone_para = doc.add_paragraph()
            tone_label = tone_para.add_run("Tone: ")
            tone_label.bold = True
            tone_run = tone_para.add_run(voiceover.get('tone', ''))
            tone_run.font.italic = True

            duration_run = tone_para.add_run(f" | Duration: ~{voiceover.get('duration_sec', '?')} sec")
            duration_run.font.italic = True

            # Script box
            script_para = doc.add_paragraph(voiceover.get('script', ''), style='List Paragraph')
            script_para.paragraph_format.left_indent = Inches(0.5)
            script_para.paragraph_format.right_indent = Inches(0.5)

            # Shading for script box
            shading_elm = script_para._element
            shading_elm.get_or_add_pPr().append(
                doc.styles._element.makeelement('{http://schemas.openxmlformats.org/wordprocessingml/2006/main}shd',
                {'val': 'auto', 'fill': 'E8E8E8'})
            )

            # Delivery notes
            delivery_heading = doc.add_heading('Delivery Notes:', level=4)
            delivery_para = doc.add_paragraph(voiceover.get('delivery_notes', ''), style='List Paragraph')
            delivery_para.paragraph_format.left_indent = Inches(0.25)

            # AI VO option
            ai_vo = voiceover.get('ai_option', {})
            if ai_vo:
                ai_heading = doc.add_heading('AI Voiceover Option:', level=4)
                ai_para = doc.add_paragraph()
                ai_para.add_run(f"Tool: {ai_vo.get('tool', 'N/A')}\n")
                ai_para.add_run(f"Voice: {ai_vo.get('voice', 'N/A')}\n")
                ai_para.add_run(f"Speed: {ai_vo.get('speed', 'N/A')}")

            doc.add_paragraph("─" * 40)

        # Page break between posts
        doc.add_page_break()

    # Save the document
    doc.save(output_path)
    print(f"✅ Document saved to: {output_path}")

def main():
    parser = argparse.ArgumentParser(
        description="Export caption data to formatted .docx file"
    )
    parser.add_argument('--brand', required=True, help='Brand name (OutAtlas or Travel in Pride)')
    parser.add_argument('--date-range', required=True, help='Date range for the content (e.g., "Mar 28 - Apr 3, 2026")')
    parser.add_argument('--output', required=True, help='Output .docx file path')
    parser.add_argument('--captions', required=True, help='Input JSON file with caption data')

    args = parser.parse_args()

    # Load caption data
    with open(args.captions, 'r') as f:
        data = json.load(f)

    posts = data.get('posts', [])

    # Create the document
    create_docx_from_captions(args.brand, args.date_range, posts, args.output)

if __name__ == '__main__':
    main()
